(define (domain fritandoDomain)
	(:types ovo frigideira fogao oleo prato tempero mesa)
	(:predicates
		(fogaoDesligado ?fog - fogao)
		(frigideiraNoFogao ?frig - frigideira ?fog - fogao)	
		(oleoNaFrigideira ?ol - oleo ?frig - frigideira)
		(ovoNaFrigideira ?ov - ovo ?frig - frigideira)
		(ovoPronto ?ovoP - ovo ?temp - tempero)
		(ovoProntoPrato ?ovoP - ovo ?prat - prato)
		(pratoMesa ?prat - prato ?m - mesa)
	)
	(:action prepararFrigideiraFogao
		:parameters (?fog - fogao ?frig - frigideira)
		:precondition (and (not (fogaoDesligado ?fog)) (not (frigideiraNoFogao ?frig ?fog)))
		:effect (and (not(fogaoDesligado ?fog)) (frigideiraNoFogao ?frig ?fog))
	)
	(:action prepararOvo 
		:parameters (?ol - oleo ?ov - ovo ?ovoP - ovo ?temp - tempero ?frig - frigideira)
		:precondition (and (not(oleoNaFrigideira ?ol ?frig))
				(not(ovoNaFrigideira ?ov ?frig))
				(not(ovoPronto ?ovoP ?temp)))
		:effect (and (oleoNaFrigideira ?ol ?frig)
			     (ovoNaFrigideira ?ov ?frig)
			     (ovoPronto ?ovoP ?temp))
	)
	(:action finalizar
		:parameters (?ovoP - ovo ?prat - prato ?m - mesa)
		:precondition (and (ovoPronto ?ovoP)
				(not(pratoMesa ?prat ?m))
				(not(ovoProntoPrato ?ovoP ?prat)))
		:effect (and (pratoMesa ?prat ?m) (ovoProntoPrato ?ovoP ?prat))
	)
)
