(define (domain fecharGarrafaDomain)
    (:requirements :strips)
    (:types garrafa tampa mesa)
    (:predicates
        (garrafa-chao ?g - garrafa)
        (tampa-chao ?t - tampa)
        (Ngarrafa-mesa ?g - garrafa ?m - mesa)
        (Ntampa-mesa ?t - tampa ?m - mesa)
        (tampada ?g - garrafa ?t -tampa)
    )
    (:action PEGAR
        :parameters (?g - garrafa ?t - tampa ?m - mesa)
        :precondition (and (garrafa-chao ?g) (tampa-chao ?t) )
        :effect (and (not(garrafa-chao ?g)) 
                 (not(tampa-chao ?t)) 
                 (Ngarrafa-mesa ?g ?m)
                 (Ntampa-mesa ?t ?m) )
    )
    (:action COLOCAR-NA-MESA
        :parameters (?g - garrafa ?t - tampa ?m - mesa)
        :precondition (and (Ngarrafa-mesa ?g ?m) 
                       (Ntampa-mesa ?t ?m) )
        :effect (and (not(Ngarrafa-mesa ?g ?m)) 
                 (not(Ntampa-mesa ?t ?m)) 
                 (not(tampada ?g)) )
    )
    (:action TAMPAR
        :parameters (?g - garrafa ?t - tampa)
        :precondition (and (not(tampada ?g)) )
        :effect (and (tampada ?g ?t) )
    )
)
