(define (domain beijuDomain)
	(:types fogao oleo frigideira massa ovo prato mesa manteiga salada queijo mortadela)
	(:predicates
		(fogaoDesligado ?fog - fogao)
		(oleoFrigideira ?ol - oleo ?frig - frigideira)
		(frigNoFogao ?frigFogao - frigideira ?fog - fogao)
		(massaFrigideira ?m - massa ?frig - frigideira)
		(ovoPronto ?ovoP - ovo ?frig - frigideira)
		(pratoMesa ?prat - prato ?mes - mesa)
		(massaPrato ?bPronto - massa ?prat - prato)
		(manteigaMassa ?mant - manteiga ?bPronto - massa)
		(saladaMassa ?salad - salada ?bPronto - massa)
		(ovoMassa ?ovoPronto - ovo ?bPronto - massa)
		(queijoMassa ?qj - queijo ?bPronto - massa)
		(mortadelaMassa ?mort - mortadela ?bPronto - massa)
		(beijuPronto ?bPronto - massa)
	)
	(:action prepararFogao
		:parameters (?fog - fogao)
		:precondition (fogaoDesligado ?fog)
		:effect (not (fogaoDesligado ?fog))
	)
	(:action prepararFrigideira
		:parameters (?frig - frigideira ?frigFogao - frigideira ?ol - oleo ?fog - fogao)
		:precondition (and (not (oleoFrigideira ?ol ?frig)) 
			      (not (frigNoFogao ?frigFogao ?fog)))
		:effect (and (oleoFrigideira ?ol ?frig) (frigNoFogao ?frigFogao ?fog))
	)
	(:action prepararMassaOvo
		:parameters (?bPronto - massa ?m - massa ?frigFogao - frigideira ?ovoP - ovo)
		:precondition (and(frigNoFogao ?frigFogao ?fog)(not(massaFrigideira ?m ?frigFogao)) (not(ovoPronto ?ovoP ?frigFogao)))
		:effect ((massaFrigideira ?m ?frigFogao)
			(beijuPronto ?bPronto)
			(ovoPronto ?ovoP ?frigFogao))
	)
	(:action desligarFogao
		:parameters (?fog - fogao ?bPronto - massa ?ovoP - ovo ?frigFogao - frigideira ?mes - mesa)
		:precondition (and ((beijuPronto ?bPronto) (frigNoFogao ?frigFogao ?fog) (ovoPronto ?ovoP ?frigFogao)))
		:effect (fogaoDesligado ?fog)
	)	
	(:action finalizarBeiju
		:parameters (?prat - prato ?bPronto - massa ?ovoP - ovo ?qj - queijo ?salad - salada ?mort - mortadela ?fog - fogao ?mes - mesa ?mant - manteiga)
		:precondition (and((fogaoDesligado ?fog) (pratoMesa ?prat ?mes)))
		:effect ((pratoMesa ?prat ?mes)
			 (massaPrato ?bPronto ?prat)
			 (manteigaMassa ?mant ?bPronto)
			 (ovoMassa ?ovoP ?bPronto)
			 (queijoMassa ?qj ?bPronto)
			 (mortadelaMassa ?mort ?bPronto)
			 (saladaMassa ?salad ?bPronto)
			 (beijuPronto ?bPronto)
			)
	)
)
